In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

In [21]:
T = 50

pdir = r'p:\11210264-001-just-equitable-paths\wellbeing'
df = pd.read_csv(os.path.join(pdir, 'data', '3-input', 'EW', 'asphalt_based', 'database_monthly.csv'))
csv_out = os.path.join(pdir, 'data', '4-output', f'database_monthly_T{T}.csv')
csv_interim = os.path.join(pdir, 'data', '4-output', f'database_monthly_T{T}_interim.csv')

import tomli
with open("config.toml", mode="rb") as fp:
    config = tomli.load(fp)

In [22]:
df_hh = df[['IDazone', f'SD_{T}_RP', 'I_hh', 'PotDamStr', 'Pop2016', f'EW_SD_{T}_RP_hh']].copy()  # Note Income and I_hh are the same, they are the values derived from the survey. We need to have all vars at household level
df.columns

Index(['IDazone', 'I_interviewed', 'Income', 'inner_ring', 'SD_2_RP',
       'SD_5_RP', 'SD_10_RP', 'SD_20_RP', 'SD_50_RP', 'SD_100_RP', 'Buildings',
       'EAD', 'PotDamStr', 'Pop2016', 'I_hh', 'I_cap', 'I_area', 'EW',
       'EW_SD_50_RP', 'EW_SD_100_RP', 'SD_50_RP_hh', 'SD_100_RP_hh',
       'EW_SD_50_RP_hh', 'EW_SD_100_RP_hh', 'diff_SD-EW_50_RP',
       'diff_SD-EW_100_RP'],
      dtype='object')

In [23]:
extreme_poverty = config['macro']['extremepoverty']
poverty = config['macro']['poverty']
rho = config['macro']['rho']
eta = config['macro']['eta']
pi = config['macro']['pi']
hh = config["macro"]["hh"]
avg_inc = config["income"]["innerring"]

In [24]:
df_hh = df_hh.rename(columns={f"SD_{T}_RP": "dk", "I_hh": "cons_hh", "PotDamStr": "k"})
df_hh['v'] = df_hh["dk"] / df_hh["k"]
df_hh['k'] = df_hh['k'] / df_hh['Pop2016'] * hh
df_hh['dk'] = df_hh['dk'] / df_hh['Pop2016'] * hh

In [25]:
df_hh

,IDazone,dk,cons_hh,k,Pop2016,EW_SD_50_RP_hh,v
0,2,205.973062,4142.857143,20512.383740,10585.906134,214.685981,0.010041
1,3,805.485323,5505.050505,53019.573428,10140.183770,548.098821,0.015192
2,4,160.487124,4132.743363,8354.273908,8841.221453,167.890350,0.019210
3,5,707.101352,4579.439252,32076.699365,10626.233395,634.171049,0.022044
4,6,553.713469,4505.747126,41701.143430,9789.973342,508.836274,0.013278
5,7,141.212091,5386.792453,19697.636727,11837.112483,99.270387,0.007169
6,8,208.375449,3850.000000,11636.533636,7652.628484,242.436862,0.017907
7,9,430.836303,4113.095238,26472.130195,18170.615019,453.944063,0.016275
8,11,627.554130,4551.401869,45951.045585,11489.024542,568.036986,0.013657
9,12,95.563053,4331.034483,17182.959175,17551.909929,93.184945,0.005562
10,13,671.264913,3976.744186,24505.153910,17159.249752,743.953281,0.027393
11,14,739.361303,5372.549020,64338.296951,13054.359032,521.830350,0.011492
12,15,322.000213,3616.666667,32796.433092,16078.903642,411.468537,0.009818
13,16,132.948560,3868.686869,19919.096927,15290.399556,153.561189,0.006674
14,17,422.139183,5152.173913,34891.026672,8499.500975,317.258373,0.012099
15,18,382.726611,4418.032787,28028.964390,12322.100864,362.233369,0.013655
16,21,510.381386,3856.000000,39461.328415,13699.595216,592.423786,0.012934
17,22,2244.723293,3974.358974,48673.831410,18792.503841,2490.034557,0.046118
18,23,931.613194,3850.877193,36337.299893,14202.624740,1083.525971,0.025638
19,24,167.117347,3316.326531,16977.734882,13150.932211,243.208530,0.009843
20,25,134.749488,3382.857143,15184.565579,17563.583610,190.346473,0.008874
21,26,1839.244654,5866.666667,48285.391776,2992.707298,1137.615710,0.038091
22,94,428.856090,4557.377049,112194.912740,11532.535534,387.420269,0.003822
23,95,423.145054,4944.444444,59086.669752,8520.725849,338.264338,0.007161
24,96,433.952568,4635.294118,58079.787327,12844.232775,382.181373,0.007472
25,97,895.846935,3691.489362,80004.037174,14234.462052,1110.131889,0.011198
26,98,1786.330708,4029.702970,58709.180650,13560.572288,1940.865807,0.030427
27,99,513.072945,4666.666667,100650.922923,13295.261357,447.313640,0.005098

In [26]:
def optimize_reco(x):
    isBankrupt = False
    last_integ = 0.
    last_lambda = 0.
    _lambda = 0.
    opt_timestep = 0.01

    while True:
        c0 = x['cons_hh']-x['v']*x['k'] * _lambda   # I don't understand why * lambda only. Should it not be lambda * exp(-lambda*t)? Yes but for t=0, exp()=1
       
        if c0 <= extreme_poverty: #  per month
            isBankrupt = True
            return [last_lambda, isBankrupt]

        t_max = 10 # years
        dt = 52 # 52 weeks in a year
        nsteps = dt * t_max 

        integ = 0
        for _t in np.linspace(0, t_max, nsteps):
            # k, v are not time dependent, dt (weeks/year) * _t is in years, consumption is per month
            integ += (x['cons_hh'] - _lambda * x['k'] * x['v'] * np.exp(-_lambda * _t))**(-eta) * (x['k'] * x['v'] * (_lambda * _t - 1)) * np.exp(-_t * (rho + _lambda)) * dt

#         print(last_integ, integ)
        if (last_integ < 0 and integ > 0) or (last_integ > 0 and integ < 0):
            return [(_lambda + last_lambda)/2, isBankrupt]

        last_integ = integ
        if last_integ is None:
            assert(False)

        last_lambda = _lambda
        _lambda += opt_timestep

        # check for runaway
        if _lambda > 10:
            return [last_lambda, isBankrupt]

In [27]:
df_hh['opt'] = df_hh.apply(lambda x: optimize_reco(x), axis=1)
df_hh[['opt_lambda', 'isBankrupt']] = df_hh.opt.tolist()

In [28]:
df_hh['reco_time'] = np.log(1/0.05) / df_hh['opt_lambda']
df_hh.to_csv(csv_interim)

In [39]:
# I think this is wrong because it is not accounting for the change in utility! See comment in word document

def integrate_wellbeing(x):
    x_max = 10
    tstep_n = 52 * x_max  # 52 weeks in a year
    dt = 52
    
    x['c_t'] = 0
    x['w_final'] = 0
    x['c_loss'] = 0
    x['weeks_pov'] = 0
    
    for _t in np.linspace(0, x_max, tstep_n):
        # consumption at time t
        x['c_t'] =  x['cons_hh'] + (x['opt_lambda'] * x['v']* x['k']) * np.e**(-x['opt_lambda']*_t)
        
        # change in consumption
        x['c_loss'] += dt*(x['cons_hh'] - x['c_t'])

        x.loc[x['c_t'] < poverty, 'weeks_pov'] += 1

        x['w_final'] += dt * (x['c_t'])**(1-eta) * np.e**(-rho*_t) / (1-eta)


    return x

In [45]:
# I think this is correct! Use this function instead!
def w_integ(x):
    x_max = 10
    tstep_n = 52 * x_max  # 52 weeks in a year
    dt = 52
    x['c_reco'] = 0
    x['w'] = 0
    x['delta_u'] = 0
    x['u0'] = x['cons_hh']**(1-eta)/(1-eta)

    for _t in np.linspace(0, x_max, tstep_n):
        x['c_reco'] = x['opt_lambda'] * x['v'] * x['k'] * np.e**(-x['opt_lambda'] * _t)
        x['delta_u'] = (x['cons_hh'] - x['c_reco'])**(1-eta)/(1-eta)
        x['w'] += (x['u0'] - x['delta_u']) * np.e**(-rho*_t) * dt
    return x['w']

In [46]:
df_hh['w'] = df_hh.apply(lambda x: w_integ(x), axis=1)
df_hh

0      2.956609
1     12.514766
2      2.150954
3     13.619300
4     11.406912
5      1.183759
6      3.450548
7     10.249281
8     12.471106
9      1.087632
10    15.179168
11    12.004303
12     9.294440
13     1.915607
14     6.148336
15     7.702830
16    12.522419
17    44.307335
18    20.828337
19     3.365817
20     2.453779
21    23.309223
22     9.302852
23     7.028724
24     9.255665
25    21.117434
26    35.447729
27    10.390735
dtype: float64

In [47]:
# convert to equivalent wellbeing losses (monetary terms)
df['wellbeing_losses'] = df_hh['w'] / avg_inc**-(eta)

0     8.217795e+05
1     3.478438e+06
2     5.978505e+05
3     3.785439e+06
4     3.170513e+06
5     3.290219e+05
6     9.590683e+05
7     2.848753e+06
8     3.466302e+06
9     3.023036e+05
10    4.218999e+06
11    3.336556e+06
12    2.583359e+06
13    5.324365e+05
14    1.708909e+06
15    2.140976e+06
16    3.480565e+06
17    1.231508e+07
18    5.789167e+06
19    9.355176e+05
20    6.820196e+05
21    6.478721e+06
22    2.585697e+06
23    1.953610e+06
24    2.572581e+06
25    5.869520e+06
26    9.852578e+06
27    2.888070e+06
dtype: float64

In [48]:
df_hh.to_csv(csv_out, index=False)